#!/usr/bin/env python3
"""
Script để extract và convert skill data từ vibenro.sql sang PostgreSQL format
"""

import re
import json

# Đọc vibenro.sql
with open('vibenro.sql', 'r', encoding='utf-8') as f:
    content = f.read()

# Extract skill_template INSERT statements
pattern = r"INSERT INTO `skill_template`.*?VALUES\s+(.*?);"
matches = re.findall(pattern, content, re.DOTALL)

if not matches:
    print("Không tìm thấy skill data!")
    exit(1)

# Parse values
skills_by_race = {
    0: [],  # Trái Đất
    1: [],  # Namek
    2: []   # Saiyan
}

for match in matches:
    # Split by "),(" to get individual skill rows
    rows = re.split(r'\),\s*\(', match)
    
    for row in rows:
        row = row.strip('()')
        
        # Parse row - format: (nclass_id, id, name, max_point, mana_use_type, type, icon_id, dam_info, slot, skills)
        parts = []
        current = ''
        in_string = False
        bracket_count = 0
        
        for char in row:
            if char == "'" and (not current or current[-1] != '\\'):
                in_string = not in_string
            elif char == '[' and not in_string:
                bracket_count += 1
            elif char == ']' and not in_string:
                bracket_count -= 1
            elif char == ',' and not in_string and bracket_count == 0:
                parts.append(current.strip())
                current = ''
                continue
            
            current += char
        
        if current:
            parts.append(current.strip())
        
        if len(parts) < 10:
            continue
        
        nclass_id = int(parts[0])
        skill_id = int(parts[1])
        name = parts[2].strip("'")
        max_point = int(parts[3])
        mana_use_type = int(parts[4])
        skill_type = int(parts[5])
        icon_id = int(parts[6])
        dam_info = parts[7].strip("'")
        slot = int(parts[8])
        skills_json_str = parts[9].strip("'")
        
        # Parse skills JSON - it's escaped
        # Format: '["{\\"power_require\\":1000,...}",...]'
        try:
            # Remove outer brackets and split
            skills_json_str = skills_json_str.strip('[]')
            
            # Split by "},"{
            skill_levels = []
            level_strings = re.findall(r'\{[^}]+\}', skills_json_str)
            
            for level_str in level_strings:
                # Unescape
                level_str = level_str.replace('\\"', '"')
                level_obj = json.loads(level_str)
                skill_levels.append(level_obj)
            
            if not skill_levels:
                continue
                
            skill_data = {
                'nclass_id': nclass_id,
                'skill_id': skill_id,
                'name': name,
                'max_point': max_point,
                'mana_use_type': mana_use_type,
                'skill_type': skill_type,
                'icon_id': icon_id,
                'dam_info': dam_info,
                'slot': slot,
                'skill_levels': skill_levels
            }
            
            if nclass_id in skills_by_race:
                skills_by_race[nclass_id].append(skill_data)
                
        except Exception as e:
            print(f"Error parsing skill {name}: {e}")
            continue

# Sort by slot
for race in skills_by_race:
    skills_by_race[race].sort(key=lambda s: (s['slot'], s['skill_id']))

# Generate SQL
print("-- Full skill data imported from vibenro.sql")
print("-- Generated by extract_skills.py")
print()
print("-- Xóa data cũ")
print("TRUNCATE TABLE skill_template CASCADE;")
print()
print("-- Import skills cho từng hành tinh")
print()

race_names = {
    0: 'TRÁI ĐẤT',
    1: 'NAMEK',
    2: 'SAIYAN'
}

for race_id, skills in skills_by_race.items():
    if not skills:
        continue
        
    print(f"-- ==========================================")
    print(f"-- {race_names[race_id]} (nclass_id = {race_id})")
    print(f"-- {len(skills)} skills")
    print(f"-- ==========================================")
    print()
    
    for skill in skills:
        skill_levels_json = json.dumps(skill['skill_levels'], ensure_ascii=False)
        
        print(f"INSERT INTO skill_template")
        print(f"(nclass_id, skill_id, name, max_point, mana_use_type, skill_type, icon_id, dam_info, slot, skill_levels)")
        print(f"VALUES")
        print(f"({skill['nclass_id']}, {skill['skill_id']}, '{skill['name']}', {skill['max_point']}, "
              f"{skill['mana_use_type']}, {skill['skill_type']}, {skill['icon_id']}, "
              f"'{skill['dam_info']}', {skill['slot']},")
        print(f"'{skill_levels_json}'::jsonb);")
        print()

print("-- Done!")
print(f"-- Total skills imported:")
for race_id, skills in skills_by_race.items():
    print(f"--   {race_names[race_id]}: {len(skills)} skills")
